SELECT * FROM 
(SELECT (first_name||' '||last_name) as "SKI JUMPER", name as "COUNTRY", world_cup_wins as "WC WINS"
FROM ski_jumpers NATURAL JOIN countries NATURAL JOIN hills
NATURAL JOIN 
(SELECT * FROM (SELECT COUNT(HILL_ID) AS "HILL_COUNT", COUNTRY_CODE
FROM HILLS
GROUP BY COUNTRY_CODE 
ORDER BY HILL_COUNT DESC)
WHERE HILL_COUNT < 3) 
WHERE POPULATION < 30000000
ORDER BY WORLD_CUP_WINS DESC)
WHERE ROWNUM <=1;