INSERT ALL
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(1, 1, 'SVN', '22-MAR-2008', '19-MAR-2011')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(2, 1, 'FRA', '20-MAR-2011', '23-MAR-2013')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(3, 1, 'RUS', '24-MAR-2013', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(4, 2, 'USA', '17-MAR-2007', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(5, 3, 'POL', '22-MAR-2009', '19-MAR-2011')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(6, 3, 'AUT', '23-MAR-2014', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(7, 4, 'AUT', '24-MAR-2003', '22-MAR-2014')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(8, 4, 'BGR', '23-MAR-2014', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(9, 5, 'CZE', '19-MAR-2006', '21-MAR-2009')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(10, 5, 'RUS', '21-MAR-2010', '23-MAR-2013')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(11, 5, 'CZE', '23-MAR-2014', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(12, 6, 'GER', '23-MAR-2008', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(13, 7, 'NOR', '24-MAR-2011', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(14, 8, 'NOR', '25-MAR-2002', '23-MAR-2011')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(15, 9, 'CZE', '22-MAR-2009', '22-MAR-2014')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(16, 10, 'POL', '19-MAR-2006', '21-MAR-2009')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(17, 11, 'FIN', '21-MAR-2010', '22-MAR-2014')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(18, 12, 'JPN', '20-MAR-2005', '21-MAR-2010')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(19, 12, 'FIN', '23-MAR-2014', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(20, 13, 'RUS', '21-MAR-2004', '21-MAR-2010')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(21, 14, 'BGR', '23-MAR-2008', '22-MAR-2014')
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(22, 15, 'POL', '20-MAR-2011', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(23, 16, 'JPN', '21-MAR-2010', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(24, 17, 'FRA', '24-MAR-2013', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(25, 18, 'EST', '23-MAR-2008', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(26, 19, 'SVN', '20-MAR-2011', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(27, 20, 'SUI', '23-MAR-2008', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(28, 21, 'ITA', '18-MAR-2007', NULL)
   INTO COACHING_JOB_ASSIGNMENTS(assignment_id, coach_id, country_code, job_started, job_finished)
   VALUES(29, 22, 'KOR', '23-MAR-2008', NULL)
SELECT 1 FROM DUAL;