INSERT ALL
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(1, 'MATJAZ', 'ZUPAN', '27-SEP-1968', 'SLOVENIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(2, 'CLINT', 'JONES', '05-OCT-1984', 'UNITED STATES', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(3, 'HEINZ', 'KUTTIN', '05-JAN-1971', 'AUSTRIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(4, 'ALEXANDER', 'POINTNER', '01-JAN-1971', 'AUSTRIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(5, 'RICHARD', 'SHALLERT', '21-APR-1964', 'AUSTRIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(6, 'WERNER', 'SCHUSTER', '04-SEP-1969', 'AUSTRIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(7, 'ALEXANDER', 'STOECKL', '11-DEC-1973', 'AUSTRIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(8, 'MIKA', 'KOJONKOSKI', '19-APR-1963', 'FINLAND', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(9, 'DAVID', 'JIROUTEK', '02-MAR-1973', 'CZECH REPUBLIC', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(10, 'HANNU', 'LEPISTOE', '17-MAY-1946', 'FINLAND', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(11, 'PEKKA', 'NIEMELA', '06-MAR-1974', 'FINLAND', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(12, 'KARI', 'YLIANTTILA', '28-AUG-1953', 'FINLAND', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(13, 'WOLFGANG', 'STEIERT', '19-APR-1963', 'GERMANY', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(14, 'JOACHIM', 'WINTERLICH', '17-MAR-1942', 'GERMANY', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(15, 'LUKASZ', 'KRUCZEK', '01-NOV-1975', 'POLAND', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(16, 'TOMOHARU', 'YOKOKAWA', '14-FEB-1957', 'JAPAN', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(17, 'GERARD', 'COLIN', '08-OCT-1967', 'FRANCE', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(18, 'TAMBET', 'PIKKOR', '11-JAN-1978', 'ESTONIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(19, 'GORAN', 'JANUS', '27-MAR-1970', 'SLOVENIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(20, 'MARTIN', 'KUENZLE', '24-NOV-1973', 'AUSTRIA', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(21, 'ROBERTO', 'CECON', '28-DEC-1971', 'ITALY', NULL)
   INTO COACHES(coach_id, first_name, last_name, date_of_birth, nationality, phone_number)
   VALUES(22, 'WOLFGANG', 'HARTMANN', '17-APR-1973', 'GERMANY', NULL)
SELECT 1 FROM DUAL;  