INSERT ALL
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(1, 'AUT', 225, 200, NULL, 'TAUPLITZ', '8982')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(2, 'AUT', 130, 120, 'BERGISEL WEG 3', 'INNSBRUCK', '6020')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(3, 'AUT', 140, 125, 'ROSENTHAL', 'BISCHOFSHOFEN', '5500')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(4, 'CZE', 205, 185, 'HORNI ROKYTNICE 702', 'HARRACHOV', '512-45')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(5, 'CZE', 134, 120, 'HORNI ROKYTNICE 702', 'HARRACHOV', '512-45')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(6, 'CZE', 134, 120, 'JESTEDSKA 50 HORNI HANYCHOW', 'LIBEREC', '460-08')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(7, 'FIN', 127, 120, 'TAHKOLAHDENTIE 3', 'KUOPIO', '73310')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(8, 'FIN', 142, 120, 'RUKATUNTURINTIE 9', 'RUKA', '93825')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(9, 'FIN', 130, 116, 'SALPAUSSELANKATU', 'LAHTI', '15110')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(10, 'GER', 213, 185, 'BIRGSAUTAL', 'OBERSTDORF', '87561')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(11, 'GER', 140, 125, 'FURSTENSTRASSE 9', 'GARMISCH-PARTENKIRCHEN', '82467')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(12, 'GER', 140, 125, NULL, 'KLINGENTAL', '08428')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(13, 'GER', 145, 130, 'ZUR HOPPECKE 5', 'WILLINGEN', '34508')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(14, 'ITA', 140, 125, 'FRAZIONE PLAN', 'PRAGELATO', '10060')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(15, 'JPN', 134, 120, 'TEINE WARD', 'SAPPORO', '593')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(16, 'NOR', 225, 200, 'HEGGENASEN 60', 'VIKERSUND', '3370')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(17, 'NOR', 138, 123, NULL, 'LILLEHAMMER', '2601')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(18, 'NOR', 134, 120, 'TRYVANNSVEIEN 64', 'OSLO', '0791')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(19, 'POL', 134, 120, 'MALINKA 8', 'WISLA', '43-460')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(20, 'POL', 134, 120, 'ALEJA 3 MAJA 5', 'ZAKOPANE', '34500')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(21, 'SVN', 225, 200, NULL, 'RATECE', '4283')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(22, 'SWE', 124, 115, 'LUGNETVAGEN', 'FALUN', '79131')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(23, 'SUI', 137, 125, 'BANKLIALPWEG 25', 'ENGELBERG', '6390')
   INTO HILLS(hill_id, country_code, hill_size, critical_point, address, city, postal_code)
   VALUES(24, 'USA', 134, 120, 'POWDER MOUNTAIN ROAD', 'UTAH', '84310')
SELECT 1 FROM DUAL;