INSERT ALL
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(1, 'GER', 'SEVERIN', 'FREUND', '11-MAY-1988', '22-DEC-2007', NULL, 21)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(2, 'SVN', 'PETER', 'PREVC', '20-SEP-1992', '05-DEC-2009', NULL, 20)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(3, 'GER', 'STEFAN', 'KRAFT', '13-MAY-1993', '03-JAN-2008', NULL, 4)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(4, 'NOR', 'ANDERS', 'FANNEMEL', '13-MAY-1991', '13-DEC-2008', NULL, 3)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(5, 'GER', 'MICHAEL', 'HAYBOECK', '05-MAR-1991', '03-MAR-2008', NULL, 4)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(6, 'JPN', 'NORIAKI', 'KASAI', '06-JUN-1972', '20-DEC-1989', NULL, 17)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(7, 'CZE', 'ROMAN', 'KOUDELKA', '09-JUL-1989', '07-FEB-2004', NULL, 5)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(8, 'NOR', 'RUNE', 'VELTA', '19-JUL-1989', '07-MAR-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(9, 'POL', 'KAMIL', 'STOCH', '25-MAY-1987', '17-JAN-2004', NULL, 15)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(10, 'AUT', 'GREGOR', 'SCHLIERENZAUER', '07-JAN-1990', '12-MAR-2006', NULL, 53)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(11, 'SUI', 'SIMON', 'AMMAN', '25-JUN-1981', '29-DEC-1997', NULL, 23)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(12, 'GER', 'RICHARD', 'FREITAG', '14-AUG-1991', '17-JAN-2009', NULL, 5)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(13, 'SVN', 'JURIJ', 'TEPES', '14-FEB-1989', '03-JAN-2004', NULL, 2)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(14, 'SVN', 'JERNEJ', 'DAMJAN', '28-MAY-1983', '01-JAN-2003', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(15, 'GER', 'MARKUS', 'EISENBICHLER', '03-APR-1991', '04-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(16, 'JPN', 'DAIKI', 'ITO', '27-DEC-1985', '13-MAR-2002', NULL, 4)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(17, 'NOR', 'ANDERS', 'JACOBSEN', '17-FEB-1985', '05-DEC-2004', NULL, 10)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(18, 'NOR', 'ANDERS', 'BARDAL', '24-AUG-1982', '03-FEB-2001', NULL, 7)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(19, 'POL', 'PIOTR', 'ZYLA', '16-JAN-1987', '21-JAN-2006', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(20, 'JPN', 'TAKU', 'TAKEUCHI', '20-MAY-1987', '24-NOV-2006', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(21, 'GER', 'MICHAEL', 'NEUMAYER', '15-JAN-1979', '24-JAN-2002', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(22, 'GER', 'MARINUS', 'KRAUS', '13-FEB-1991', '17-FEB-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(23, 'NOR', 'JOHAN ANDRE', 'FORFANG', '04-JUL-1995', '24-JAN-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(24, 'SVN', 'NEJC', 'DEZMAN', '07-DEC-1992', '09-FEB-2010', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(25, 'SVN', 'MATJAZ', 'PUNGERTAR', '14-AUG-1990', '11-MAR-2008', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(26, 'SVN', 'ROBERT', 'KRANJEC', '16-JUL-1981', '13-MAR-1998', NULL, 6)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(27, 'SUI', 'GREGOR', 'DESCHWANDEN', '27-FEB-1991', '13-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(28, 'AUT', 'ANDREAS', 'KOFLER', '17-MAY-1984', '11-MAR-2000', NULL, 12)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(29, 'FIN', 'LAURI', 'ASIKAINEN', '28-MAY-1989', '12-FEB-2006', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(30, 'AUT', 'MANUEL', 'FETTNER', '17-JUN-1985', '12-JAN-2002', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(31, 'RUS', 'DMITRY', 'VASSILIEV', '26-DEC-1979', '27-NOV-1999', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(32, 'GER', 'ANDREAS', 'WELLINGER', '28-AUG-1995', '27-FEB-2012', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(33, 'NOR', 'ANDREAS', 'STJERNEN', '30-JUL-1988', '05-MAR-2003', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(34, 'NOR', 'MANUEL', 'POPPINGER', '19-MAY-1989', '04-DEC-2006', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(35, 'NOR', 'TOM', 'HILDE', '22-SEP-1987', '05-DEC-2005', NULL, 3)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(36, 'CZE', 'JAN', 'MATURA', '29-JAN-1980', '07-FEB-1998', NULL, 2)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(37, 'NOR', 'KENNETH', 'GANGNESS', '15-MAY-1989', '09-MAR-2008', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(38, 'POL', 'KLEMENS', 'MURANKA', '23-NOV-1994', '21-JAN-2011', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(39, 'AUT', 'THOMAS', 'DIETHART', '25-FEB-1992', '03-JAN-2011', NULL, 2)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(40, 'JPN', 'JUNISHIRO', 'KOBAYASHI', '11-JUN-1991', '11-JAN-2009', NULL, 0 )
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(41, 'JPN', 'SHOHEI', 'TOCHIMOTO', '21-DEC-1989', '21-JAN-2006', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(42, 'RUS', 'VLADISLAV', 'BOYARINTSEV', '31-OCT-1994', '21-NOV-2014', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(43, 'POL', 'ALEKSANDER', 'ZNISZCZOL', '08-MAR-1994', '30-NOV-2011', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(44, 'JPN', 'KENTO', 'SAKUYAMA', '03-JUL-1990', '16-JAN-2010', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(45, 'POL', 'JAN', 'ZIOBRO', '24-JUN-1991', '27-NOV-2011', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(46, 'GER', 'ANDREAS', 'WANK', '18-FEB-1988', '19-FEB-2004', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(47, 'ITA', 'DAVIDE', 'BRESADOLA', '10-SEP-1988', '15-DEC-2007', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(48, 'FIN', 'VILLE', 'LARINTO', '11-APR-1990', '01-DEC-2007', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(49, 'POL', 'DAWID', 'KUBACKI', '12-MAR-1990', '16-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(50, 'SVN', 'ANZE', 'SEMENIC', '01-AUG-1993', '08-JAN-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(51, 'CZE', 'JAKUB', 'JANDA', '27-APR-1978', '09-MAR-1997', NULL, 6)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(52, 'RUS', 'ILMIR', 'HAZETDINOW', '28-OCT-1991', '03-MAR-2012', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(53, 'FIN', 'JANNE', 'AHONEN', '11-MAY-1977', '29-DEC-1993', NULL, 36)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(54, 'CZE', 'ANTONIN', 'HAJEK', '12-FEB-1987', '10-JAN-2004', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(55, 'SVN', 'ANZE', 'LANISEK', '20-APR-1996', '20-MAR-2014', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(56, 'FIN', 'SAMI', 'NIEMI', '16-FEB-1991', '01-DEC-2007', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(57, 'FIN', 'ANSSI', 'KOIVURANTA', '03-JUL-1988', '05-MAR-2004', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(58, 'POL', 'MACIEJ', 'KOT', '09-JUN-1991', '13-DEC-2007', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(59, 'SUI', 'KILLIAN', 'PEIER', '28-MAR-1995', '08-FEB-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(60, 'BGR', 'VLADIMIR', 'ZOGRAFSKI', '14-JUL-1993', '13-DEC-2008', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(61, 'AUT', 'WOLFGANG', 'LOITZL', '13-JAN-1980', '06-DEC-1997', NULL, 4)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(62, 'SVN', 'TOMAZ', 'NAGLIC', '18-JUL-1989', '09-JAN-2011', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(63, 'RUS', 'DENIS', 'KORNILOV', '17-AUG-1986', '20-DEC-2003', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(64, 'NOR', 'ROBERT', 'JOHANSSON', '23-MAR-1990', '28-NOV-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(65, 'GER', 'KARL', 'GEIGER', '11-FEB-1993', '23-NOV-2012', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(66, 'CZE', 'LUKAS', 'HLAVA', '10-SEP-1984', '11-JAN-2003', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(67, 'POL', 'STEFAN', 'HULA', '29-SEP-1986', '29-DEC-2005', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(68, 'NOR', 'OLE MARIUS', 'INGVALDSEN', '02-OCT-1985', '06-DEC-2008', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(69, 'KOR', 'SEOU', 'CHOI', '03-DEC-1983', '14-DEC-2012', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(70, 'FIN', 'HARRI', 'OLLI', '15-JAN-1984', '29-NOV-2002', NULL, 3)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(71, 'GER', 'PIUS', 'PASCHKE', '20-MAY-1990', '20-DEC-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(72, 'NOR', 'JOACHIM', 'HAUER', '02-FEB-1991', '24-JAN-2014', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(73, 'JPN', 'RYOYU', 'KOBAYASHI', '13-APR-1998', '22-JAN-2016', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(74, 'POL', 'KRZYSZTOF', 'BIEGUN', '21-MAY-1994', '16-FEB-2013', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(75, 'SVN', 'JAKA', 'HVALA', '15-JUL-1993', '19-JAN-2012', NULL, 1)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(76, 'JPN', 'YUTA', 'WATASE', '08-AUG-1982', '23-JAN-1999', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(77, 'RUS', 'MIKHAIL', 'MAKSIMOCHKIN', '29-AUG-1993', '22-NOV-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(78, 'CAN', 'MACKENZIE', 'BOYD-CLOWES', '07-JUL-1991', '24-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(79, 'FIN', 'OLLI', 'MUOTKA', '14-JUL-1988', '17-JAN-2010', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(80, 'ITA', 'ROBERTO', 'DELLASEGA', '15-JUN-1990', '14-DEC-2008', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(81, 'EST', 'KAREEL', 'NURMSALU', '30-APR-1991', '28-NOV-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(82, 'FRA', 'RONAN LAMY', 'CHAPPUIS', '10-SEP-1993', '23-NOV-2012', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(83, 'RUS', 'ALEXEY', 'ROMASHOV', '29-APR-1992', '23-NOV-2012', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(84, 'SVN', 'ROBERT', 'HRGOTA', '02-AUG-1988', '11-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(85, 'SVN', 'CENE', 'PREVC', '12-MAR-1996', '03-JAN-2013', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(86, 'AUT', 'MARTIN', 'KOCH', '22-JAN-1982', '04-JAN-1999', '26-JAN-2014', 5)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(87, 'USA', 'NICHOLAS', 'FAIRALL', '06-JUL-1989', '01-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(88, 'POL', 'KRZYSZTOF', 'MIETUS', '03-AUG-1991', '17-JAN-2009', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(89, 'ITA', 'SEBASTIAN', 'COLOREDO', '09-SEP-1987', '10-DEC-2005', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(90, 'RUS', 'ILJA', 'ROSLIAKOV', '18-FEB-1983', '21-DEC-2002', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(91, 'USA', 'PETER', 'FRENETTE', '24-FEB-1992', '15-JAN-2011', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(92, 'ITA', 'ANDREA', 'MORASSI', '30-AUG-1988', '18-DEC-2005', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(93, 'GER', 'FELIX', 'SHOFT', '06-JUL-1990', '29-NOV-2008', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(94, 'RUS', 'ANTON', 'KALINITSCHENKO', '22-JUL-1982', '28-NOV-1999', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(95, 'AUT', 'DAVID', 'ZAUNER', '09-APR-1985', '29-NOV-2003', NULL, 0)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(96, 'POL', 'ADAM', 'MALYSZ', '03-DEC-1977', '30-NOV-1996', '19-MAR-2011', 39)
   INTO SKI_JUMPERS(ski_jumper_id, country_code, first_name, last_name, date_of_birth, first_start_date, date_retired, world_cup_wins)
   VALUES(97, 'NOR', 'DANIEL ANDRE', 'TANDE', '24-JAN-1994', '06-DEC-2013', NULL, 1)
SELECT 1 FROM DUAL;